apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 300
        - key: "postgres-only"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
      - name: frontend
        image: frontend:0.7.1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 75m
            memory: 128Mi
          limits:
            cpu: 150m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 7
          periodSeconds: 10
