apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  PROJECT_NAME: kube-essentials
  SECRET_KEY: verysecret
  FIRST_SUPERUSER: admin@example.com
  FIRST_SUPERUSER_PASSWORD: dW5pcXVlLXBhc3N3b3Jk
  POSTGRES_SERVER: postgres-postgresql.postgres.svc.cluster.local
  POSTGRES_PORT: "5432"
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: 4KjuZ1F8Hb
